"use client";

import messages from "../messages/messages";

export function validateEmail(value) {
  let callback = {
    valid: true,
    message: "",
  };
  if (!value) {
    callback.valid = false;
    callback.message = "empty";
    return callback;
  }
  const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailPattern.test(value)) {
    callback.valid = false;
    callback.message = "invalid";
    return callback;
  }
  return callback;
}

export function validateText(value) {
  let callback = {
    valid: true,
    message: "",
  };

  if (!value) {
    callback.valid = false;
    callback.message = "empty";
    return callback;
  }
  return callback;
}

export const skills = [
  {
    img: "/images/skills/html.svg",
    name: "html",
    label: "HTML",
    class: "",
    cate: "language",
    url: null,
  },
  {
    img: "/images/skills/css.svg",
    name: "css",
    label: "CSS",
    class: "",
    cate: "language",
    url: null,
  },
  {
    img: "/images/skills/less.svg",
    name: "less",
    label: "Less",
    class: "size-leg",
    cate: "framework&labary",
    url: null,
  },
  {
    img: "/images/skills/scss.svg",
    name: "scss",
    label: "Scss",
    class: "size-leg",
    cate: "framework&labary",
    url: null,
  },
  {
    img: "/images/skills/tailwind.svg",
    name: "tailwind",
    label: "Tailwind",
    class: "size-leg",
    cate: "framework&labary",
    url: null,
  },
  {
    img: "/images/skills/js.svg",
    name: "js",
    label: "JavaScript",
    class: "",
    cate: "language",
    url: null,
  },
  {
    img: "/images/skills/sql.svg",
    name: "sql",
    label: "SQL",
    class: "",
    cate: "language",
    url: null,
  },
  {
    img: "/images/skills/jquery.svg",
    name: "jquery",
    label: "JQuery",
    class: "size-leg",
    cate: "framework&labary",
    url: null,
  },
  {
    img: "/images/skills/reactjs.svg",
    name: "reactjs",
    label: "ReactJS",
    class: "",
    cate: "framework&labary",
    url: null,
  },
  {
    img: "/images/skills/nextjs.svg",
    name: "nextjs",
    label: "NextJS",
    class: "size-leg theme-dark-invert",
    cate: "framework&labary",
    url: null,
  },
  {
    img: "/images/skills/php.svg",
    name: "php",
    label: "PHP",
    class: "size-leg",
    cate: "language",
    url: null,
  },
  {
    img: "/images/skills/vue.svg",
    name: "vue",
    label: "Vue",
    class: "size-leg",
    cate: "framework&labary",
    url: null,
  },
  {
    img: "/images/skills/angular.svg",
    name: "angular",
    label: "Angular",
    class: "size-leg",
    cate: "framework&labary",
    url: null,
  },
  {
    img: "/images/skills/mysql.svg",
    name: "mysql",
    label: "MySQL",
    class: "size-leg",
    cate: "tool",
    url: null,
  },
  {
    img: "/images/skills/mongodb.svg",
    name: "mongodb",
    label: "MongoDB",
    class: "size-leg",
    cate: "framework&labary",
    url: null,
  },
  {
    img: "/images/skills/vscode.svg",
    name: "vscode",
    label: "VS Code",
    class: "",
    cate: "tool",
    url: null,
  },
  {
    img: "/images/skills/postman.svg",
    name: "postman",
    label: "Postman",
    class: "",
    cate: "tool",
    url: null,
  },
  {
    img: "/images/skills/sourcetree.svg",
    name: "sourcetree",
    label: "Sourcetree",
    class: "",
    cate: "tool",
    url: null,
  },
  {
    img: "/images/skills/filezilla.svg",
    name: "filezilla",
    label: "FileZilla",
    class: "",
    cate: "tool",
    url: null,
  },
  {
    img: "/images/skills/figma.svg",
    name: "figma",
    label: "Figma",
    class: "",
    cate: "tool",
    url: null,
  },
  {
    img: "/images/skills/postgresSQL.svg",
    name: "postgresSQL",
    label: "PostgresSQL",
    class: "",
    cate: "tool",
    url: null,
  },
  {
    img: "/images/skills/fibery.png",
    name: "fibery",
    label: "Fibery",
    class: "",
    cate: "tool",
    url: null,
  },
  {
    img: "/images/skills/sketch.svg",
    name: "sketch",
    label: "Sketch",
    class: "",
    cate: "tool",
    url: null,
  },
];

export const projects = {
  en: [
    {
      img: "/images/projects/project1.png",
      name: "Business Website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2022",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","sketch","fibery"],
    },
    {
      img: "/images/projects/project2.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2022",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","sketch","fibery"],
    },
    {
      img: "/images/projects/project3.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2022",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project4.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2022",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project5.jpg",
      name: "CMS (Content Management System)",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2023",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project6.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2023",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project7.png",
      name: "Business Website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2023",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project8.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2024",
      positions: ["frontend developer"],
      tools: ["html","less","js","reactjs","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project9.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2024",
      positions: ["frontend developer"],
      tools: ["html","less","js","nextjs","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project10.png",
      name: "Business Website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2024",
      positions: ["frontend developer"],
      tools: ["html","less","js","nextjs","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project.png",
      name: "Kasidit Katcharoen Portfolio",
      url:'#',
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat, officiis. Obcaecati cum magni possimus repellat!",
      address: '',
      year: "2025",
      positions: ["full stack developer"],
      tools: ["html","scss","tailwind","js","nextjs","mongodb","sourcetree"],
    },
  ],
  th: [
    {
      img: "/images/projects/project1.png",
      name: "Business Website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2022",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","sketch","fibery"],
    },
    {
      img: "/images/projects/project2.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2022",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","sketch","fibery"],
    },
    {
      img: "/images/projects/project3.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2022",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project4.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2022",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project5.jpg",
      name: "CMS (Content Management System)",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2023",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project6.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2023",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project7.png",
      name: "Business Website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2023",
      positions: ["frontend developer"],
      tools: ["html","less","js","jquery","php","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project8.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2024",
      positions: ["frontend developer"],
      tools: ["html","less","js","reactjs","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project9.png",
      name: "e-commerce website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2024",
      positions: ["frontend developer"],
      tools: ["html","less","js","nextjs","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project10.png",
      name: "Business Website",
      url: "",
      desc: "",
      address: 'orisma technology company limited',
      year: "2024",
      positions: ["frontend developer"],
      tools: ["html","less","js","nextjs","sourcetree","figma","fibery"],
    },
    {
      img: "/images/projects/project.png",
      name: "Kasidit Katcharoen Portfolio",
      url:'#',
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat, officiis. Obcaecati cum magni possimus repellat!",
      address: '',
      year: "2025",
      positions: ["full stack developer"],
      tools: ["html","scss","tailwind","js","nextjs","mongodb","sourcetree"],
    },
  ],
}
